name: flutter_realm_provider
description: A realm provider for flutter realm.
publish_to: none
version: 1.0.2
homepage:
environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"
# dependencies
dependencies:
  flutter:
    sdk: flutter
  realm: 1.5.0
# dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
